"""creazione tabella import_inventario

Revision ID: 059e7545f4a3
Revises: de6201d2a2a8
Create Date: 2025-09-24 07:38:20.213679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059e7545f4a3'
down_revision = 'de6201d2a2a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventario_id', sa.Integer(), nullable=True),
    sa.Column('articolo_id', sa.String(length=255), nullable=True),
    sa.Column('descrizione_articolo', sa.String(length=255), nullable=True),
    sa.Column('quantita_esistente', sa.Integer(), nullable=False),
    sa.Column('costo', sa.Numeric(), nullable=True),
    sa.Column('utente_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['articolo_id'], ['articoli.cod_art'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inventario_id'], ['inventari.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utente_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import_inventario')
    # ### end Alembic commands ###
