"""aggiunta tabella CashCheckEvent

Revision ID: 0725eea0bc9e
Revises: 4c80c44d6a56
Create Date: 2026-03-20 19:57:24.530865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0725eea0bc9e'
down_revision = '4c80c44d6a56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_check_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('amount_spese', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('customer_charge_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['check_id'], ['cash_checks.id'], name=op.f('fk_cash_check_events_check_id_cash_checks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], name=op.f('fk_cash_check_events_created_by_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_check_events'))
    )
    with op.batch_alter_table('cash_check_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_check_events_check_id'), ['check_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_check_events_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_check_events_to_status'), ['to_status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_check_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_check_events_to_status'))
        batch_op.drop_index(batch_op.f('ix_cash_check_events_event_date'))
        batch_op.drop_index(batch_op.f('ix_cash_check_events_check_id'))

    op.drop_table('cash_check_events')
    # ### end Alembic commands ###
