"""add id_art to sincro

Revision ID: 0b012adc130a
Revises: f4013c7edad7
Create Date: 2026-01-05 18:50:28.548546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b012adc130a'
down_revision = 'f4013c7edad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sincro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_art', sa.BigInteger(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sincro_id_art'), ['id_art'], unique=False)
        batch_op.create_foreign_key(None, 'articoli', ['id_art'], ['id_art'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sincro', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sincro_id_art'))
        batch_op.drop_column('id_art')

    # ### end Alembic commands ###
