"""aggiunta campi export_inventario e fix_movements su tabella inventari

Revision ID: 0b0dc8fe99e4
Revises: 90ea8defc04c
Create Date: 2025-09-23 19:41:34.516051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b0dc8fe99e4'
down_revision = '90ea8defc04c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventari', schema=None) as batch_op:
        batch_op.add_column(sa.Column('export_inventario', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fix_movements', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventari', schema=None) as batch_op:
        batch_op.drop_column('fix_movements')
        batch_op.drop_column('export_inventario')

    # ### end Alembic commands ###
