"""aggiunta flag agenda su payments e moves

Revision ID: 149261200f9b
Revises: 472dac3838fd
Create Date: 2026-02-17 18:43:16.244827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '149261200f9b'
down_revision = '472dac3838fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_expense_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flag', sa.String(length=2), nullable=False))

    with op.batch_alter_table('cash_moves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flag', sa.String(length=2), nullable=True))

    with op.batch_alter_table('cash_sale_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flag', sa.String(length=2), nullable=False))

    with op.batch_alter_table('pos_moves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flag', sa.String(length=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pos_moves', schema=None) as batch_op:
        batch_op.drop_column('flag')

    with op.batch_alter_table('cash_sale_payments', schema=None) as batch_op:
        batch_op.drop_column('flag')

    with op.batch_alter_table('cash_moves', schema=None) as batch_op:
        batch_op.drop_column('flag')

    with op.batch_alter_table('cash_expense_payments', schema=None) as batch_op:
        batch_op.drop_column('flag')

    # ### end Alembic commands ###
