"""modifica campi POS tabella spese

Revision ID: 15a4c6a026ce
Revises: 201b32dcbed1
Create Date: 2026-04-10 16:25:43.107774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15a4c6a026ce'
down_revision = '201b32dcbed1'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('cash_expense_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pos_card_label', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pos_is_personal', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.drop_constraint('cash_expense_payments_pos_device_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('cash_expense_payments_pos_circuit_id_fkey', type_='foreignkey')
        batch_op.drop_column('pos_device_id')
        batch_op.drop_column('pos_circuit_id')

    with op.batch_alter_table('cash_expense_payments', schema=None) as batch_op:
        batch_op.alter_column('pos_is_personal', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_expense_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pos_circuit_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pos_device_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('cash_expense_payments_pos_circuit_id_fkey', 'pos_circuits', ['pos_circuit_id'], ['id'])
        batch_op.create_foreign_key('cash_expense_payments_pos_device_id_fkey', 'pos_devices', ['pos_device_id'], ['id'])
        batch_op.drop_column('pos_is_personal')
        batch_op.drop_column('pos_card_label')

    # ### end Alembic commands ###
