"""creazione tabella articoli

Revision ID: 1b800ea05a3e
Revises: c757e3f527fa
Create Date: 2025-01-21 22:39:04.853152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b800ea05a3e'
down_revision = 'c757e3f527fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articoli',
    sa.Column('cod_art', sa.String(length=255), nullable=False),
    sa.Column('descrizione', sa.String(length=255), nullable=True),
    sa.Column('descrizione_aggiuntiva', sa.Text(), nullable=True),
    sa.Column('prezzo', sa.Numeric(), nullable=True),
    sa.Column('giacenza', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('cod_art')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articoli')
    # ### end Alembic commands ###
