"""creazione tabelle Giacenze e Barcode e modifica di quella Articoli con eliminazione del campo giacenza

Revision ID: 1e5a71348f41
Revises: 1b800ea05a3e
Create Date: 2025-02-26 12:17:36.219376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e5a71348f41'
down_revision = '1b800ea05a3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barcode',
    sa.Column('cod_bar', sa.String(length=255), nullable=False),
    sa.Column('cod_art', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('cod_bar')
    )
    op.create_table('giacenza',
    sa.Column('cod_art', sa.String(length=255), nullable=False),
    sa.Column('giac_neg', sa.Integer(), nullable=True),
    sa.Column('giac_www', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('cod_art')
    )
    with op.batch_alter_table('articoli', schema=None) as batch_op:
        batch_op.drop_column('giacenza')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articoli', schema=None) as batch_op:
        batch_op.add_column(sa.Column('giacenza', sa.INTEGER(), autoincrement=False, nullable=True))

    op.drop_table('giacenza')
    op.drop_table('barcode')
    # ### end Alembic commands ###
