"""aggiunta tabella check

Revision ID: 201b32dcbed1
Revises: e14a0e9f2c8b
Create Date: 2026-04-01 16:15:43.834491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201b32dcbed1'
down_revision = 'e14a0e9f2c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_row_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash_day_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('is_checked', sa.Boolean(), nullable=False),
    sa.Column('checked_by_user_id', sa.Integer(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cash_day_id'], ['cash_days.id'], name=op.f('fk_cash_row_checks_cash_day_id_cash_days')),
    sa.ForeignKeyConstraint(['checked_by_user_id'], ['user.id'], name=op.f('fk_cash_row_checks_checked_by_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_row_checks')),
    sa.UniqueConstraint('entity_type', 'entity_id', name='uq_cash_row_check_entity')
    )
    with op.batch_alter_table('cash_row_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_row_checks_cash_day_id'), ['cash_day_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_row_checks_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_row_checks_entity_type'), ['entity_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_row_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_row_checks_entity_type'))
        batch_op.drop_index(batch_op.f('ix_cash_row_checks_entity_id'))
        batch_op.drop_index(batch_op.f('ix_cash_row_checks_cash_day_id'))

    op.drop_table('cash_row_checks')
    # ### end Alembic commands ###
