"""inserimento campo deposito nelle tabelle inventario

Revision ID: 28b3efbd1b91
Revises: a4cb349b6e60
Create Date: 2025-10-07 17:42:37.786024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28b3efbd1b91'
down_revision = 'a4cb349b6e60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deposito', sa.String(length=10), nullable=True))

    with op.batch_alter_table('inventari', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deposito', sa.String(length=10), nullable=True))

    with op.batch_alter_table('inventario_export', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deposito', sa.String(length=10), nullable=True))

    with op.batch_alter_table('inventario_righe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deposito', sa.String(length=10), nullable=True))

    with op.batch_alter_table('inventario_righe_versioni', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deposito', sa.String(length=10), nullable=True))

    with op.batch_alter_table('rettifiche_inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deposito', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rettifiche_inventario', schema=None) as batch_op:
        batch_op.drop_column('deposito')

    with op.batch_alter_table('inventario_righe_versioni', schema=None) as batch_op:
        batch_op.drop_column('deposito')

    with op.batch_alter_table('inventario_righe', schema=None) as batch_op:
        batch_op.drop_column('deposito')

    with op.batch_alter_table('inventario_export', schema=None) as batch_op:
        batch_op.drop_column('deposito')

    with op.batch_alter_table('inventari', schema=None) as batch_op:
        batch_op.drop_column('deposito')

    with op.batch_alter_table('import_inventario', schema=None) as batch_op:
        batch_op.drop_column('deposito')

    # ### end Alembic commands ###
