"""Aggiunta tabella Inventario

Revision ID: 2ae3c3f4bf02
Revises: 2f3e85787e8f
Create Date: 2025-04-02 09:19:46.578513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ae3c3f4bf02'
down_revision = '2f3e85787e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_inventario', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_inventario')
    )
    op.create_table('schede_prodotti',
    sa.Column('descrizione', sa.String(length=5000), nullable=True),
    sa.Column('short', sa.String(length=5000), nullable=True),
    sa.Column('cod_art', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('cod_art')
    )
    op.create_table('sincro',
    sa.Column('cod_art', sa.String(length=255), nullable=False),
    sa.Column('prestashop', sa.Boolean(), nullable=True),
    sa.Column('poleepo', sa.Boolean(), nullable=True),
    sa.Column('teamsystem', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('cod_art')
    )
    op.create_table('inventario_righe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventario_id', sa.Integer(), nullable=True),
    sa.Column('articolo_id', sa.String(length=255), nullable=True),
    sa.Column('descrizione_articolo', sa.String(length=255), nullable=True),
    sa.Column('barcode_articolo', sa.String(length=50), nullable=True),
    sa.Column('quantita_inserita', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['articolo_id'], ['articoli.cod_art'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inventario_id'], ['inventari.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utente_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventario_righe')
    op.drop_table('sincro')
    op.drop_table('schede_prodotti')
    op.drop_table('inventari')
    # ### end Alembic commands ###
