"""cambio struttura users e ruoli

Revision ID: 2c64ba002f4a
Revises: 28b3efbd1b91
Create Date: 2025-11-25 16:21:23.959406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c64ba002f4a'
down_revision = '28b3efbd1b91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_inventario', schema=None) as batch_op:
        batch_op.alter_column('deposito',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('inventari', schema=None) as batch_op:
        batch_op.alter_column('deposito',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('inventario_export', schema=None) as batch_op:
        batch_op.alter_column('deposito',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('inventario_righe', schema=None) as batch_op:
        batch_op.alter_column('deposito',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('inventario_righe_versioni', schema=None) as batch_op:
        batch_op.alter_column('deposito',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('rettifiche_inventario', schema=None) as batch_op:
        batch_op.alter_column('deposito',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_role_id_fkey', type_='foreignkey')
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('user_role_id_fkey', 'roles', ['role_id'], ['id'])

    with op.batch_alter_table('rettifiche_inventario', schema=None) as batch_op:
        batch_op.alter_column('deposito',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('inventario_righe_versioni', schema=None) as batch_op:
        batch_op.alter_column('deposito',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('inventario_righe', schema=None) as batch_op:
        batch_op.alter_column('deposito',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('inventario_export', schema=None) as batch_op:
        batch_op.alter_column('deposito',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('inventari', schema=None) as batch_op:
        batch_op.alter_column('deposito',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('import_inventario', schema=None) as batch_op:
        batch_op.alter_column('deposito',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    op.drop_table('user_roles')
    # ### end Alembic commands ###
