"""aggiunta campo is_default nella tabella PosDevices

Revision ID: 2dc6c7166c86
Revises: e69414835af3
Create Date: 2026-03-11 16:46:27.594936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dc6c7166c86'
down_revision = 'e69414835af3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pos_devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pos_devices', schema=None) as batch_op:
        batch_op.drop_column('is_default')

    # ### end Alembic commands ###
