"""Aggiunta tabella Sincro

Revision ID: 2f3e85787e8f
Revises: 1e5a71348f41
Create Date: 2025-03-17 17:00:36.325316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f3e85787e8f'
down_revision = '1e5a71348f41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schede_prodotti',
    sa.Column('descrizione', sa.String(length=255), nullable=False),
    sa.Column('cod_art', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('descrizione')
    )
    op.create_table('sincro',
    sa.Column('cod_art', sa.String(length=255), nullable=False),
    sa.Column('prestashop', sa.Boolean(), nullable=True),
    sa.Column('poleepo', sa.Boolean(), nullable=True),
    sa.Column('teamsystem', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('cod_art')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sincro')
    op.drop_table('schede_prodotti')
    # ### end Alembic commands ###
