"""Correzione definizione tabella ter trello_actions

Revision ID: 38cd6a24c476
Revises: 814d990eae80
Create Date: 2025-06-07 09:31:59.312455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38cd6a24c476'
down_revision = '814d990eae80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trello_actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ordine', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trello_actions', schema=None) as batch_op:
        batch_op.drop_column('ordine')

    # ### end Alembic commands ###
