"""Modifica tabella Trello Config

Revision ID: 39785d6ef039
Revises: 9547161f3927
Create Date: 2025-05-05 12:17:17.847431

"""
from alembic import op
import sqlalchemy as sa

from tools.crypto import EncryptedString

# revision identifiers, used by Alembic.
revision = '39785d6ef039'
down_revision = '9547161f3927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trello_configs', schema=None) as batch_op:
        batch_op.alter_column('api_key',
               existing_type=sa.VARCHAR(length=128),
               type_=EncryptedString(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trello_configs', schema=None) as batch_op:
        batch_op.alter_column('api_key',
               existing_type=EncryptedString(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
