"""Correzione definizione tabella trello_actions

Revision ID: 39a11a6ccab7
Revises: ff1ef31e84a8
Create Date: 2025-06-07 09:06:11.309368

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '39a11a6ccab7'
down_revision = 'ff1ef31e84a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trello_connections', schema=None) as batch_op:
        batch_op.drop_column('ordine')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trello_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ordine', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
