"""aggiunta tabella OrderStatus

Revision ID: 3c63b6a42c06
Revises: c73df253eba3
Create Date: 2026-02-04 18:36:17.692430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c63b6a42c06'
down_revision = 'c73df253eba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('slack_reaction', sa.String(length=64), nullable=True),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('order_statuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_statuses_order_index'), ['order_index'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_statuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_statuses_order_index'))

    op.drop_table('order_statuses')
    # ### end Alembic commands ###
