"""aggiuntatabelle per conteggi fondocassa cashdrawercount e cashdrawercountline

Revision ID: 3edd29b6d3ea
Revises: db627141d5e7
Create Date: 2026-03-16 19:39:48.547983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3edd29b6d3ea'
down_revision = 'db627141d5e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_drawer_counts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash_day_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cash_day_id'], ['cash_days.id'], name=op.f('fk_cash_drawer_counts_cash_day_id_cash_days'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], name=op.f('fk_cash_drawer_counts_created_by_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_drawer_counts')),
    sa.UniqueConstraint('cash_day_id', name='uq_cash_drawer_count_day')
    )
    with op.batch_alter_table('cash_drawer_counts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_drawer_counts_cash_day_id'), ['cash_day_id'], unique=False)

    op.create_table('cash_drawer_count_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drawer_count_id', sa.Integer(), nullable=False),
    sa.Column('denomination', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('denomination > 0', name=op.f('ck_cash_drawer_count_lines_ck_drawer_count_line_denomination_pos')),
    sa.CheckConstraint('line_total >= 0', name=op.f('ck_cash_drawer_count_lines_ck_drawer_count_line_total_nonneg')),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_cash_drawer_count_lines_ck_drawer_count_line_quantity_nonneg')),
    sa.ForeignKeyConstraint(['drawer_count_id'], ['cash_drawer_counts.id'], name=op.f('fk_cash_drawer_count_lines_drawer_count_id_cash_drawer_counts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_drawer_count_lines')),
    sa.UniqueConstraint('drawer_count_id', 'denomination', name='uq_cash_drawer_count_line_denomination')
    )
    with op.batch_alter_table('cash_drawer_count_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_drawer_count_lines_drawer_count_id'), ['drawer_count_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_drawer_count_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_drawer_count_lines_drawer_count_id'))

    op.drop_table('cash_drawer_count_lines')
    with op.batch_alter_table('cash_drawer_counts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_drawer_counts_cash_day_id'))

    op.drop_table('cash_drawer_counts')
    # ### end Alembic commands ###
