"""Aggiunta tabella moduli di importazione

Revision ID: 446247b4e46f
Revises: bca9ee52b115
Create Date: 2025-04-20 09:29:59.011551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '446247b4e46f'
down_revision = 'bca9ee52b115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moduli_importazione',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descrizione', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moduli_importazione')
    # ### end Alembic commands ###
