"""aggiunta campi anomalia e rimanenza di cassa

Revision ID: 472dac3838fd
Revises: 5f5a75ca1411
Create Date: 2026-02-12 09:27:24.051991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '472dac3838fd'
down_revision = '5f5a75ca1411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_closures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('closing_cash_drawer', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('anomaly_flag', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('anomaly_note', sa.Text(), nullable=True))

    # with op.batch_alter_table('pos_device_circuits', schema=None) as batch_op:
    #     batch_op.create_unique_constraint('uq_pos_device_circuit', ['pos_device_id', 'pos_circuit_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('pos_device_circuits', schema=None) as batch_op:
    #     batch_op.drop_constraint('uq_pos_device_circuit', type_='unique')

    with op.batch_alter_table('cash_closures', schema=None) as batch_op:
        batch_op.drop_column('anomaly_note')
        batch_op.drop_column('anomaly_flag')
        batch_op.drop_column('closing_cash_drawer')

    # ### end Alembic commands ###
