"""Aggiunta tabella inventario_export

Revision ID: 48c801ce398b
Revises: 524e44070897
Create Date: 2025-04-11 16:54:39.306901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c801ce398b'
down_revision = '524e44070897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventario_export',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventario_id', sa.Integer(), nullable=True),
    sa.Column('articolo_id', sa.String(length=255), nullable=True),
    sa.Column('descrizione_articolo', sa.String(length=255), nullable=True),
    sa.Column('barcode_articolo', sa.String(length=50), nullable=True),
    sa.Column('giacenza', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['articolo_id'], ['articoli.cod_art'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inventario_id'], ['inventari.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventario_export')
    # ### end Alembic commands ###
