"""add id_art to immagini

Revision ID: 490fa9619af2
Revises: 98d256e04e8c
Create Date: 2026-01-05 17:40:21.561850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490fa9619af2'
down_revision = '98d256e04e8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('immagini', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_art', sa.BigInteger(), nullable=True))
        batch_op.create_index(batch_op.f('ix_immagini_id_art'), ['id_art'], unique=False)
        batch_op.create_foreign_key(None, 'articoli', ['id_art'], ['id_art'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('immagini', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_immagini_id_art'))
        batch_op.drop_column('id_art')

    # ### end Alembic commands ###
