"""aggiunta tabella CashEcommerce

Revision ID: 4c80c44d6a56
Revises: 3edd29b6d3ea
Create Date: 2026-03-18 18:42:37.225523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c80c44d6a56'
down_revision = '3edd29b6d3ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_ecommerce',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash_day_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['cash_day_id'], ['cash_days.id'], name=op.f('fk_cash_ecommerce_cash_day_id_cash_days'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], name=op.f('fk_cash_ecommerce_created_by_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_ecommerce'))
    )
    with op.batch_alter_table('cash_ecommerce', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_ecommerce_cash_day_id'), ['cash_day_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_ecommerce', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_ecommerce_cash_day_id'))

    op.drop_table('cash_ecommerce')
    # ### end Alembic commands ###
