"""Aggiunta campi tabella inventario_riga

Revision ID: 524e44070897
Revises: e5f6bc284981
Create Date: 2025-04-02 12:37:08.262951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524e44070897'
down_revision = 'e5f6bc284981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario_righe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_pedane', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('num_cartoni', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('num_pezzi_sciolti', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pezzi_per_collo', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('colli_per_pedana', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario_righe', schema=None) as batch_op:
        batch_op.drop_column('colli_per_pedana')
        batch_op.drop_column('pezzi_per_collo')
        batch_op.drop_column('num_pezzi_sciolti')
        batch_op.drop_column('num_cartoni')
        batch_op.drop_column('num_pedane')

    # ### end Alembic commands ###
