"""creazione tabelle per agenda

Revision ID: 5f5a75ca1411
Revises: c03a84207c0b
Create Date: 2026-02-12 07:04:35.603575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f5a75ca1411'
down_revision = 'c03a84207c0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_name')
    )
    op.create_table('cash_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_date', sa.Date(), nullable=False),
    sa.Column('opening_float', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_days', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_days_day_date'), ['day_date'], unique=True)

    op.create_table('pos_circuits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pos_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cash_closures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash_day_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('counted_cash', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('counted_bank_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('counted_pos_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('owner_take_cash', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('depositable_cash', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_cash', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_bank_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_pos_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('diff_cash', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('diff_bank', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('diff_pos', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('diff_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cash_day_id'], ['cash_days.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cash_day_id', name='uq_cash_closure_day')
    )
    with op.batch_alter_table('cash_closures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_closures_cash_day_id'), ['cash_day_id'], unique=False)

    op.create_table('cash_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash_day_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('supplier', sa.String(length=160), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('doc_ref', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cash_day_id'], ['cash_days.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_expenses_cash_day_id'), ['cash_day_id'], unique=False)

    op.create_table('cash_moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash_day_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('performed_by', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("direction IN ('in','out')", name='ck_cash_move_direction'),
    sa.CheckConstraint('amount >= 0', name='ck_cash_move_amount_nonneg'),
    sa.ForeignKeyConstraint(['cash_day_id'], ['cash_days.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_moves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_moves_cash_day_id'), ['cash_day_id'], unique=False)

    op.create_table('cash_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash_day_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_label', sa.String(length=120), nullable=True),
    sa.Column('doc_ref', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cash_day_id'], ['cash_days.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['cash_customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_sales_cash_day_id'), ['cash_day_id'], unique=False)

    op.create_table('pos_device_circuits',
    sa.Column('pos_device_id', sa.Integer(), nullable=False),
    sa.Column('pos_circuit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pos_circuit_id'], ['pos_circuits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pos_device_id'], ['pos_devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pos_device_id', 'pos_circuit_id'),
    sa.UniqueConstraint('pos_device_id', 'pos_circuit_id', name='uq_pos_device_circuit')
    )
    op.create_table('pos_moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash_day_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pos_device_id', sa.Integer(), nullable=False),
    sa.Column('pos_circuit_id', sa.Integer(), nullable=False),
    sa.Column('doc_ref', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("direction IN ('in','out')", name='ck_pos_move_direction'),
    sa.CheckConstraint('amount >= 0', name='ck_pos_move_amount_nonneg'),
    sa.ForeignKeyConstraint(['cash_day_id'], ['cash_days.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['pos_circuit_id'], ['pos_circuits.id'], ),
    sa.ForeignKeyConstraint(['pos_device_id'], ['pos_devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pos_moves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pos_moves_cash_day_id'), ['cash_day_id'], unique=False)

    op.create_table('cash_closure_pos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash_closure_id', sa.Integer(), nullable=False),
    sa.Column('pos_device_id', sa.Integer(), nullable=False),
    sa.Column('pos_circuit_id', sa.Integer(), nullable=False),
    sa.Column('counted_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('diff_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['cash_closure_id'], ['cash_closures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pos_circuit_id'], ['pos_circuits.id'], ),
    sa.ForeignKeyConstraint(['pos_device_id'], ['pos_devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cash_closure_id', 'pos_device_id', 'pos_circuit_id', name='uq_cash_closure_pos_row')
    )
    with op.batch_alter_table('cash_closure_pos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_closure_pos_cash_closure_id'), ['cash_closure_id'], unique=False)

    op.create_table('cash_expense_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('method', sa.String(length=12), nullable=False),
    sa.Column('off_cash', sa.Boolean(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pos_device_id', sa.Integer(), nullable=True),
    sa.Column('pos_circuit_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.CheckConstraint("(method <> 'pos') OR (pos_device_id IS NOT NULL AND pos_circuit_id IS NOT NULL)", name='ck_cash_expense_payment_pos_requires_device_circuit'),
    sa.CheckConstraint("direction IN ('in','out')", name='ck_cash_expense_payment_direction'),
    sa.CheckConstraint('amount >= 0', name='ck_cash_expense_payment_amount_nonneg'),
    sa.ForeignKeyConstraint(['expense_id'], ['cash_expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pos_circuit_id'], ['pos_circuits.id'], ),
    sa.ForeignKeyConstraint(['pos_device_id'], ['pos_devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_expense_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_expense_payments_expense_id'), ['expense_id'], unique=False)

    op.create_table('cash_sale_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('method', sa.String(length=12), nullable=False),
    sa.Column('off_cash', sa.Boolean(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pos_device_id', sa.Integer(), nullable=True),
    sa.Column('pos_circuit_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.CheckConstraint("(method <> 'pos') OR (pos_device_id IS NOT NULL AND pos_circuit_id IS NOT NULL)", name='ck_cash_sale_payment_pos_requires_device_circuit'),
    sa.CheckConstraint("direction IN ('in','out')", name='ck_cash_sale_payment_direction'),
    sa.CheckConstraint('amount >= 0', name='ck_cash_sale_payment_amount_nonneg'),
    sa.ForeignKeyConstraint(['pos_circuit_id'], ['pos_circuits.id'], ),
    sa.ForeignKeyConstraint(['pos_device_id'], ['pos_devices.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['cash_sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_sale_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_sale_payments_sale_id'), ['sale_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_sale_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_sale_payments_sale_id'))

    op.drop_table('cash_sale_payments')
    with op.batch_alter_table('cash_expense_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_expense_payments_expense_id'))

    op.drop_table('cash_expense_payments')
    with op.batch_alter_table('cash_closure_pos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_closure_pos_cash_closure_id'))

    op.drop_table('cash_closure_pos')
    with op.batch_alter_table('pos_moves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pos_moves_cash_day_id'))

    op.drop_table('pos_moves')
    op.drop_table('pos_device_circuits')
    with op.batch_alter_table('cash_sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_sales_cash_day_id'))

    op.drop_table('cash_sales')
    with op.batch_alter_table('cash_moves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_moves_cash_day_id'))

    op.drop_table('cash_moves')
    with op.batch_alter_table('cash_expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_expenses_cash_day_id'))

    op.drop_table('cash_expenses')
    with op.batch_alter_table('cash_closures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_closures_cash_day_id'))

    op.drop_table('cash_closures')
    op.drop_table('pos_devices')
    op.drop_table('pos_circuits')
    with op.batch_alter_table('cash_days', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_days_day_date'))

    op.drop_table('cash_days')
    op.drop_table('cash_customers')
    # ### end Alembic commands ###
