"""Creazione tabelle per editor Trello

Revision ID: 6233822b2b83
Revises: 39785d6ef039
Create Date: 2025-05-05 18:15:36.504968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6233822b2b83'
down_revision = '39785d6ef039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trello_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.String(length=64), nullable=False),
    sa.Column('board_name', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=128), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('webhook_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('board_id')
    )
    op.create_table('trello_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=64), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['trello_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trello_actions')
    op.drop_table('trello_connections')
    # ### end Alembic commands ###
