"""aggiunta tabella CashReceiptClosure

Revision ID: 692e4d31dafd
Revises: 0725eea0bc9e
Create Date: 2026-03-24 09:17:37.289867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '692e4d31dafd'
down_revision = '0725eea0bc9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_receipt_closures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash_day_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('closure_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("closure_type IN ('fine_giornata','intermedia')", name=op.f('ck_cash_receipt_closures_ck_cash_receipt_closure_type')),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_cash_receipt_closures_ck_cash_receipt_closure_amount_nonneg')),
    sa.ForeignKeyConstraint(['cash_day_id'], ['cash_days.id'], name=op.f('fk_cash_receipt_closures_cash_day_id_cash_days'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], name=op.f('fk_cash_receipt_closures_created_by_user_id_user')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], name=op.f('fk_cash_receipt_closures_updated_by_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_receipt_closures'))
    )
    with op.batch_alter_table('cash_receipt_closures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_receipt_closures_cash_day_id'), ['cash_day_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_receipt_closures_closure_type'), ['closure_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_receipt_closures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_receipt_closures_closure_type'))
        batch_op.drop_index(batch_op.f('ix_cash_receipt_closures_cash_day_id'))

    op.drop_table('cash_receipt_closures')
    # ### end Alembic commands ###
