"""creazione tabella assegni emessi

Revision ID: 6c7693e36d37
Revises: 15a4c6a026ce
Create Date: 2026-04-10 19:58:15.204052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c7693e36d37'
down_revision = '15a4c6a026ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_issued_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('check_number', sa.String(length=50), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['cash_banks.id'], name=op.f('fk_cash_issued_checks_bank_id_cash_banks')),
    sa.ForeignKeyConstraint(['expense_id'], ['cash_expenses.id'], name=op.f('fk_cash_issued_checks_expense_id_cash_expenses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_issued_checks'))
    )
    with op.batch_alter_table('cash_issued_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_issued_checks_bank_id'), ['bank_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_issued_checks_expense_id'), ['expense_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_issued_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_issued_checks_expense_id'))
        batch_op.drop_index(batch_op.f('ix_cash_issued_checks_bank_id'))

    op.drop_table('cash_issued_checks')
    # ### end Alembic commands ###
