"""barcode: add surrogate pk id and unique (cod_bar,id_art)

Revision ID: 7251e6507311
Revises: 02564e1394f7
Create Date: 2026-01-07 06:05:30.262530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7251e6507311'
down_revision = '02564e1394f7'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('barcode') as batch_op:
        # 1) drop PK esistente su cod_bar
        batch_op.drop_constraint('barcode_pkey', type_='primary')

        # 2) aggiungi id come NULLABLE (per ora)
        batch_op.add_column(sa.Column('id', sa.BigInteger(), nullable=True))

    # 3) backfill: crea una sequence e popola id
    op.execute("CREATE SEQUENCE IF NOT EXISTS barcode_id_seq")
    op.execute("UPDATE barcode SET id = nextval('barcode_id_seq') WHERE id IS NULL")
    op.execute("ALTER SEQUENCE barcode_id_seq OWNED BY barcode.id")

    with op.batch_alter_table('barcode') as batch_op:
        # 4) ora puoi renderlo NOT NULL
        batch_op.alter_column('id', existing_type=sa.BigInteger(), nullable=False)

        # 5) nuova PK su id
        batch_op.create_primary_key('barcode_pkey', ['id'])

        # 6) vincolo di unicità logica (cod_bar,id_art)
        batch_op.create_unique_constraint('uq_barcode_codbar_idart', ['cod_bar', 'id_art'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barcode', schema=None) as batch_op:
        batch_op.drop_constraint('uq_barcode_codbar_idart', type_='unique')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
