"""campo is_default nella tabella PosDevices non nullable

Revision ID: 7912994a9542
Revises: 2dc6c7166c86
Create Date: 2026-03-11 16:52:08.406181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7912994a9542'
down_revision = '2dc6c7166c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pos_devices', schema=None) as batch_op:
        batch_op.alter_column('is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pos_devices', schema=None) as batch_op:
        batch_op.alter_column('is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
