"""tabella ponte tra PoMove e CashSalePayment

Revision ID: 7c42eef454d5
Revises: e350bce69087
Create Date: 2026-03-31 16:35:48.977177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c42eef454d5'
down_revision = 'e350bce69087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_sale_payment_pos_moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_payment_id', sa.Integer(), nullable=False),
    sa.Column('pos_move_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pos_move_id'], ['pos_moves.id'], name=op.f('fk_cash_sale_payment_pos_moves_pos_move_id_pos_moves'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sale_payment_id'], ['cash_sale_payments.id'], name=op.f('fk_cash_sale_payment_pos_moves_sale_payment_id_cash_sale_payments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_sale_payment_pos_moves')),
    sa.UniqueConstraint('sale_payment_id', 'pos_move_id', name='uq_sale_payment_pos_move')
    )
    with op.batch_alter_table('cash_sale_payment_pos_moves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_sale_payment_pos_moves_pos_move_id'), ['pos_move_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_sale_payment_pos_moves_sale_payment_id'), ['sale_payment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_sale_payment_pos_moves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_sale_payment_pos_moves_sale_payment_id'))
        batch_op.drop_index(batch_op.f('ix_cash_sale_payment_pos_moves_pos_move_id'))

    op.drop_table('cash_sale_payment_pos_moves')
    # ### end Alembic commands ###
