"""aggiunta colonna con logopath in PosCircuit

Revision ID: 7ee042625cc9
Revises: ed6f0371664f
Create Date: 2026-02-25 18:27:49.742739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ee042625cc9'
down_revision = 'ed6f0371664f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pos_circuits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pos_circuits', schema=None) as batch_op:
        batch_op.drop_column('logo_path')

    # ### end Alembic commands ###
