"""Correzione definizione tabella bis trello_actions

Revision ID: 814d990eae80
Revises: 39a11a6ccab7
Create Date: 2025-06-07 09:09:02.534813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '814d990eae80'
down_revision = '39a11a6ccab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trello_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ordine', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trello_connections', schema=None) as batch_op:
        batch_op.drop_column('ordine')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
