"""creazione tabella CashBank

Revision ID: 8713517447a1
Revises: 7912994a9542
Create Date: 2026-03-12 07:38:23.569442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8713517447a1'
down_revision = '7912994a9542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_banks'))
    )
    with op.batch_alter_table('cash_banks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_banks_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_banks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_banks_name'))

    op.drop_table('cash_banks')
    # ### end Alembic commands ###
