"""aggiunta tabelle CashDeposit e CashDepositCheck e aggiunta campo Deposit in CashDay

Revision ID: 891aae56a338
Revises: ec627f9faa19
Create Date: 2026-02-23 09:27:32.921660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891aae56a338'
down_revision = 'ec627f9faa19'
branch_labels = None
depends_on = None


def _pg_constraint_exists(conn, table_name: str, constraint_name: str) -> bool:
    sql = sa.text("""
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        WHERE t.relname = :table
          AND c.conname = :cname
        LIMIT 1
    """)
    return conn.execute(sql, {"table": table_name, "cname": constraint_name}).first() is not None


def _pg_index_exists(conn, index_name: str) -> bool:
    # to_regclass returns NULL if not exists
    sql = sa.text("SELECT to_regclass(:idx)")
    return conn.execute(sql, {"idx": index_name}).scalar() is not None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_deposits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash_day_id', sa.Integer(), nullable=False),
    sa.Column('deposit_date', sa.Date(), nullable=False),
    sa.Column('deposit_type', sa.String(length=32), nullable=False),
    sa.Column('cash_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cash_day_id'], ['cash_days.id'], name=op.f('fk_cash_deposits_cash_day_id_cash_days'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_deposits'))
    )
    with op.batch_alter_table('cash_deposits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_deposits_cash_day_id'), ['cash_day_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_deposits_deposit_date'), ['deposit_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_deposits_deposit_type'), ['deposit_type'], unique=False)

    op.create_table('cash_deposit_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deposit_id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.Integer(), nullable=False),
    sa.Column('check_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['check_id'], ['cash_checks.id'], name=op.f('fk_cash_deposit_checks_check_id_cash_checks')),
    sa.ForeignKeyConstraint(['deposit_id'], ['cash_deposits.id'], name=op.f('fk_cash_deposit_checks_deposit_id_cash_deposits'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_deposit_checks')),
    sa.UniqueConstraint('deposit_id', 'check_id', name='uq_deposit_check')
    )
    with op.batch_alter_table('cash_deposit_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_deposit_checks_check_id'), ['check_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_deposit_checks_deposit_id'), ['deposit_id'], unique=False)

    with op.batch_alter_table('cash_customers', schema=None) as batch_op:
        batch_op.drop_constraint('cash_customers_display_name_key', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_cash_customers_display_name'), ['display_name'])

    with op.batch_alter_table('delivery_routes', schema=None) as batch_op:
        batch_op.drop_constraint('delivery_routes_slack_channel_id_key', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_delivery_routes_slack_channel_id'), ['slack_channel_id'])

    with op.batch_alter_table('inventari', schema=None) as batch_op:
        batch_op.drop_constraint('inventari_data_inventario_key', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_inventari_data_inventario'), ['data_inventario'])

    with op.batch_alter_table('moduli_importazione', schema=None) as batch_op:
        batch_op.drop_constraint('moduli_importazione_nome_key', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_moduli_importazione_nome'), ['nome'])

    with op.batch_alter_table('order_statuses', schema=None) as batch_op:
        batch_op.drop_constraint('order_statuses_code_key', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_order_statuses_code'), ['code'])

    with op.batch_alter_table('pos_circuits', schema=None) as batch_op:
        batch_op.drop_constraint('pos_circuits_name_key', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_pos_circuits_name'), ['name'])

    conn = op.get_bind()

    # --- FIX: uq_pos_device_circuit (idempotente + riusa indice se esiste) ---
    if not _pg_constraint_exists(conn, "pos_device_circuits", "uq_pos_device_circuit"):
        if _pg_index_exists(conn, "uq_pos_device_circuit"):
            op.execute("""
                ALTER TABLE pos_device_circuits
                ADD CONSTRAINT uq_pos_device_circuit
                UNIQUE USING INDEX uq_pos_device_circuit
            """)
        else:
            op.execute("""
                ALTER TABLE pos_device_circuits
                ADD CONSTRAINT uq_pos_device_circuit
                UNIQUE (pos_device_id, pos_circuit_id)
            """)

    with op.batch_alter_table('pos_devices', schema=None) as batch_op:
        batch_op.drop_constraint('pos_devices_name_key', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_pos_devices_name'), ['name'])

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint('roles_name_key', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_roles_name'), ['name'])

    with op.batch_alter_table('slack_connections', schema=None) as batch_op:
        batch_op.drop_constraint('slack_connections_team_id_key', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_slack_connections_team_id'), ['team_id'])

    with op.batch_alter_table('trello_connections', schema=None) as batch_op:
        batch_op.drop_constraint('trello_connections_board_id_key', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_trello_connections_board_id'), ['board_id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_email_key', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')
        batch_op.create_unique_constraint('user_email_key', ['email'])

    with op.batch_alter_table('trello_connections', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_trello_connections_board_id'), type_='unique')
        batch_op.create_unique_constraint('trello_connections_board_id_key', ['board_id'])

    with op.batch_alter_table('slack_connections', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_slack_connections_team_id'), type_='unique')
        batch_op.create_unique_constraint('slack_connections_team_id_key', ['team_id'])

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_roles_name'), type_='unique')
        batch_op.create_unique_constraint('roles_name_key', ['name'])

    with op.batch_alter_table('pos_devices', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_pos_devices_name'), type_='unique')
        batch_op.create_unique_constraint('pos_devices_name_key', ['name'])

    with op.batch_alter_table('pos_device_circuits', schema=None) as batch_op:
        batch_op.drop_constraint('uq_pos_device_circuit', type_='unique')

    with op.batch_alter_table('pos_circuits', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_pos_circuits_name'), type_='unique')
        batch_op.create_unique_constraint('pos_circuits_name_key', ['name'])

    with op.batch_alter_table('order_statuses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_order_statuses_code'), type_='unique')
        batch_op.create_unique_constraint('order_statuses_code_key', ['code'])

    with op.batch_alter_table('moduli_importazione', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_moduli_importazione_nome'), type_='unique')
        batch_op.create_unique_constraint('moduli_importazione_nome_key', ['nome'])

    with op.batch_alter_table('inventari', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_inventari_data_inventario'), type_='unique')
        batch_op.create_unique_constraint('inventari_data_inventario_key', ['data_inventario'])

    with op.batch_alter_table('delivery_routes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_delivery_routes_slack_channel_id'), type_='unique')
        batch_op.create_unique_constraint('delivery_routes_slack_channel_id_key', ['slack_channel_id'])

    with op.batch_alter_table('cash_customers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_cash_customers_display_name'), type_='unique')
        batch_op.create_unique_constraint('cash_customers_display_name_key', ['display_name'])

    with op.batch_alter_table('cash_deposit_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_deposit_checks_deposit_id'))
        batch_op.drop_index(batch_op.f('ix_cash_deposit_checks_check_id'))

    op.drop_table('cash_deposit_checks')
    with op.batch_alter_table('cash_deposits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_deposits_deposit_type'))
        batch_op.drop_index(batch_op.f('ix_cash_deposits_deposit_date'))
        batch_op.drop_index(batch_op.f('ix_cash_deposits_cash_day_id'))

    op.drop_table('cash_deposits')
    # ### end Alembic commands ###
