"""add id_art to inventarioriga

Revision ID: 8ef6038c9d0e
Revises: 0b012adc130a
Create Date: 2026-01-06 09:35:15.813547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ef6038c9d0e'
down_revision = '0b012adc130a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario_righe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_art', sa.BigInteger(), nullable=True))
        batch_op.create_index(batch_op.f('ix_inventario_righe_id_art'), ['id_art'], unique=False)
        batch_op.create_foreign_key(None, 'articoli', ['id_art'], ['id_art'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario_righe', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_inventario_righe_id_art'))
        batch_op.drop_column('id_art')

    # ### end Alembic commands ###
