"""aggiunta campo has_versions su tabella inventario_riga

Revision ID: 90ea8defc04c
Revises: cf135a242fde
Create Date: 2025-08-22 12:39:00.248579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90ea8defc04c'
down_revision = 'cf135a242fde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario_righe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_versions', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario_righe', schema=None) as batch_op:
        batch_op.drop_column('has_versions')

    # ### end Alembic commands ###
