"""modifica import conflict resolutions

Revision ID: 9126721c8b3c
Revises: b8fb3f0eda6a
Create Date: 2026-01-09 07:04:16.268792

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9126721c8b3c'
down_revision = 'b8fb3f0eda6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_conflict_resolutions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entity_key', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('field', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('db_value_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('csv_value_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('action', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('mode', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.drop_index('ix_icr_type_decision')
        batch_op.drop_index('ix_icr_type_key')
        batch_op.drop_constraint('uq_icr_type_key', type_='unique')
        batch_op.create_index('ix_icr_lookup', ['type', 'entity_key', 'field'], unique=False)
        batch_op.create_unique_constraint('uq_icr_signature', ['type', 'entity_key', 'field', 'db_value_hash', 'csv_value_hash'])
        batch_op.drop_constraint('import_conflict_resolutions_created_by_fkey', type_='foreignkey')
        batch_op.drop_column('created_by')
        batch_op.drop_column('scope')
        batch_op.drop_column('key')
        batch_op.drop_column('decision')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_conflict_resolutions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decision', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('scope', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('import_conflict_resolutions_created_by_fkey', 'user', ['created_by'], ['id'])
        batch_op.drop_constraint('uq_icr_signature', type_='unique')
        batch_op.drop_index('ix_icr_lookup')
        batch_op.create_unique_constraint('uq_icr_type_key', ['type', 'key'])
        batch_op.create_index('ix_icr_type_key', ['type', 'key'], unique=False)
        batch_op.create_index('ix_icr_type_decision', ['type', 'decision'], unique=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('meta')
        batch_op.drop_column('mode')
        batch_op.drop_column('action')
        batch_op.drop_column('csv_value_hash')
        batch_op.drop_column('db_value_hash')
        batch_op.drop_column('field')
        batch_op.drop_column('entity_key')

    # ### end Alembic commands ###
