"""Aggiunta tabella Trello Config

Revision ID: 9547161f3927
Revises: 446247b4e46f
Create Date: 2025-05-04 16:55:11.630932

"""
from alembic import op
import sqlalchemy as sa

from tools.crypto import EncryptedString

# revision identifiers, used by Alembic.
revision = '9547161f3927'
down_revision = '446247b4e46f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trello_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key', EncryptedString(length=128), nullable=False),
    sa.Column('token', EncryptedString(length=256), nullable=False),
    sa.Column('id_model', sa.String(length=64), nullable=False),
    sa.Column('callback_url', sa.String(length=256), nullable=False),
    sa.Column('webhook_id', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trello_configs')
    # ### end Alembic commands ###
