"""tabelle per gestione ordini

Revision ID: 9630fe507b6e
Revises: c5a59ccb2700
Create Date: 2026-01-30 19:25:52.645148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9630fe507b6e'
down_revision = 'c5a59ccb2700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slack_channel_id', sa.String(length=50), nullable=False),
    sa.Column('default_weekday', sa.Integer(), nullable=False),
    sa.Column('default_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slack_channel_id')
    )
    op.create_table('delivery_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('override_delivery_date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['delivery_routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slack_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('slack_channel_id', sa.String(length=50), nullable=False),
    sa.Column('customer_display', sa.String(length=255), nullable=False),
    sa.Column('customer_key', sa.String(length=255), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('planned_delivery_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('slack_message_ts', sa.String(length=50), nullable=False),
    sa.Column('slack_thread_ts', sa.String(length=50), nullable=False),
    sa.Column('has_issues', sa.Boolean(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['delivery_routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slack_orders', schema=None) as batch_op:
        batch_op.create_index('ix_slack_orders_channel_customer_date', ['slack_channel_id', 'customer_key', 'order_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_slack_orders_customer_key'), ['customer_key'], unique=False)

    op.create_table('slack_order_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['slack_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slack_order_events')
    with op.batch_alter_table('slack_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slack_orders_customer_key'))
        batch_op.drop_index('ix_slack_orders_channel_customer_date')

    op.drop_table('slack_orders')
    op.drop_table('delivery_overrides')
    op.drop_table('delivery_routes')
    # ### end Alembic commands ###
