"""correzione ImportRun e ImportConflict

Revision ID: 9bcc1e2eea36
Revises: cfcb3aa5ffc0
Create Date: 2026-01-09 12:06:50.088075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bcc1e2eea36'
down_revision = 'cfcb3aa5ffc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_conflicts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('run_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_import_conflicts_run_id'), ['run_id'], unique=False)
        batch_op.create_index('ix_import_conflicts_run_status', ['run_id', 'status'], unique=False)
        batch_op.create_foreign_key(None, 'import_runs', ['run_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_conflicts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('ix_import_conflicts_run_status')
        batch_op.drop_index(batch_op.f('ix_import_conflicts_run_id'))
        batch_op.drop_column('run_id')

    # ### end Alembic commands ###
