"""creazione tabella Rettifiche inventario

Revision ID: a4cb349b6e60
Revises: bcfa5fadbfea
Create Date: 2025-09-30 07:30:12.091383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4cb349b6e60'
down_revision = 'bcfa5fadbfea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rettifiche_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventario_id', sa.Integer(), nullable=True),
    sa.Column('articolo_id', sa.String(length=255), nullable=True),
    sa.Column('giacenza', sa.Integer(), nullable=False),
    sa.Column('rilevazione', sa.Integer(), nullable=False),
    sa.Column('rettifica', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inventario_id'], ['inventari.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utente_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rettifiche_inventario')
    # ### end Alembic commands ###
