"""Aggiunto campo callback_url nella tabella trello_connections

Revision ID: ae3da00ba8aa
Revises: 59bee3029351
Create Date: 2025-05-15 14:01:48.214428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae3da00ba8aa'
down_revision = '59bee3029351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trello_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('callback_url', sa.String(length=256), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trello_connections', schema=None) as batch_op:
        batch_op.drop_column('callback_url')

    # ### end Alembic commands ###
