"""add import_runs and import_conflicts

Revision ID: b842958acc08
Revises: 2c64ba002f4a
Create Date: 2026-01-04 21:57:34.834883

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b842958acc08'
down_revision = '2c64ba002f4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_runs_task_id'), ['task_id'], unique=False)

    op.create_table('import_conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['import_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_conflicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_conflicts_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_conflicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_conflicts_run_id'))

    op.drop_table('import_conflicts')
    with op.batch_alter_table('import_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_runs_task_id'))

    op.drop_table('import_runs')
    # ### end Alembic commands ###
