"""import conflicts: add resolutions and actions

Revision ID: b8fb3f0eda6a
Revises: 7251e6507311
Create Date: 2026-01-08 19:24:34.629296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8fb3f0eda6a'
down_revision = '7251e6507311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_conflict_resolutions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'key', name='uq_icr_type_key')
    )
    with op.batch_alter_table('import_conflict_resolutions', schema=None) as batch_op:
        batch_op.create_index('ix_icr_type_decision', ['type', 'decision'], unique=False)
        batch_op.create_index('ix_icr_type_key', ['type', 'key'], unique=False)

    op.create_table('import_conflict_actions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('conflict_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('applied_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['applied_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['conflict_id'], ['import_conflicts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_conflict_actions', schema=None) as batch_op:
        batch_op.create_index('ix_ica_applied_at', ['applied_at'], unique=False)
        batch_op.create_index('ix_ica_conflict_id', ['conflict_id'], unique=False)
        batch_op.create_index('ix_ica_type_key', ['type', 'key'], unique=False)

    with op.batch_alter_table('import_conflicts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolved_by', sa.Integer(), nullable=True))
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_index('ix_import_conflicts_run_id')
        batch_op.create_index('ix_import_conflicts_type_status', ['type', 'status'], unique=False)
        batch_op.drop_constraint('import_conflicts_run_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['resolved_by'], ['id'])
        batch_op.drop_column('run_id')
        batch_op.drop_column('resolution')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_conflicts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolution', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('run_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('import_conflicts_run_id_fkey', 'import_runs', ['run_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index('ix_import_conflicts_type_status')
        batch_op.create_index('ix_import_conflicts_run_id', ['run_id'], unique=False)
        batch_op.alter_column('type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('resolved_by')

    with op.batch_alter_table('import_conflict_actions', schema=None) as batch_op:
        batch_op.drop_index('ix_ica_type_key')
        batch_op.drop_index('ix_ica_conflict_id')
        batch_op.drop_index('ix_ica_applied_at')

    op.drop_table('import_conflict_actions')
    with op.batch_alter_table('import_conflict_resolutions', schema=None) as batch_op:
        batch_op.drop_index('ix_icr_type_key')
        batch_op.drop_index('ix_icr_type_decision')

    op.drop_table('import_conflict_resolutions')
    # ### end Alembic commands ###
