"""aggiunta tabelle CashOwnerTake e CashOwnerTakeCheck

Revision ID: bc89b1fd3896
Revises: 692e4d31dafd
Create Date: 2026-03-24 17:29:13.610564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc89b1fd3896'
down_revision = '692e4d31dafd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_owner_takes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash_day_id', sa.Integer(), nullable=False),
    sa.Column('take_type', sa.String(length=20), nullable=False),
    sa.Column('cash_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('check_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("take_type IN ('parziale','serale')", name=op.f('ck_cash_owner_takes_ck_cash_owner_take_type')),
    sa.CheckConstraint('cash_amount >= 0', name=op.f('ck_cash_owner_takes_ck_cash_owner_take_cash_amount_nonneg')),
    sa.CheckConstraint('check_amount >= 0', name=op.f('ck_cash_owner_takes_ck_cash_owner_take_check_amount_nonneg')),
    sa.ForeignKeyConstraint(['cash_day_id'], ['cash_days.id'], name=op.f('fk_cash_owner_takes_cash_day_id_cash_days'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], name=op.f('fk_cash_owner_takes_created_by_user_id_user')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], name=op.f('fk_cash_owner_takes_updated_by_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_owner_takes'))
    )
    with op.batch_alter_table('cash_owner_takes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_owner_takes_cash_day_id'), ['cash_day_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_owner_takes_take_type'), ['take_type'], unique=False)

    op.create_table('cash_owner_take_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_take_id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.Integer(), nullable=False),
    sa.Column('check_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['check_id'], ['cash_checks.id'], name=op.f('fk_cash_owner_take_checks_check_id_cash_checks')),
    sa.ForeignKeyConstraint(['owner_take_id'], ['cash_owner_takes.id'], name=op.f('fk_cash_owner_take_checks_owner_take_id_cash_owner_takes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_owner_take_checks')),
    sa.UniqueConstraint('owner_take_id', 'check_id', name='uq_cash_owner_take_check')
    )
    with op.batch_alter_table('cash_owner_take_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_owner_take_checks_check_id'), ['check_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_owner_take_checks_owner_take_id'), ['owner_take_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_owner_take_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_owner_take_checks_owner_take_id'))
        batch_op.drop_index(batch_op.f('ix_cash_owner_take_checks_check_id'))

    op.drop_table('cash_owner_take_checks')
    with op.batch_alter_table('cash_owner_takes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_owner_takes_take_type'))
        batch_op.drop_index(batch_op.f('ix_cash_owner_takes_cash_day_id'))

    op.drop_table('cash_owner_takes')
    # ### end Alembic commands ###
