"""Aggiunta tabella importazioni

Revision ID: bca9ee52b115
Revises: 48c801ce398b
Create Date: 2025-04-19 17:52:24.748552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bca9ee52b115'
down_revision = '48c801ce398b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('importazioni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modulo', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('esito', sa.Boolean(), nullable=True),
    sa.Column('messaggio', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('importazioni')
    # ### end Alembic commands ###
