"""rimozione foreignkey su articolo_id dalla tabella import_inventario

Revision ID: bcfa5fadbfea
Revises: 059e7545f4a3
Create Date: 2025-09-27 07:13:00.714644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcfa5fadbfea'
down_revision = '059e7545f4a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_inventario', schema=None) as batch_op:
        batch_op.drop_constraint('import_inventario_articolo_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_inventario', schema=None) as batch_op:
        batch_op.create_foreign_key('import_inventario_articolo_id_fkey', 'articoli', ['articolo_id'], ['cod_art'], ondelete='SET NULL')

    # ### end Alembic commands ###
