"""add slack connections and actions

Revision ID: bd1592341e29
Revises: 9bcc1e2eea36
Create Date: 2026-01-15 12:19:13.570044

"""
from alembic import op
import sqlalchemy as sa
from tools.crypto import EncryptedString


# revision identifiers, used by Alembic.
revision = 'bd1592341e29'
down_revision = '9bcc1e2eea36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(length=64), nullable=False),
    sa.Column('team_name', sa.String(length=255), nullable=True),
    sa.Column('bot_user_id', sa.String(length=64), nullable=True),
    sa.Column('bot_token', EncryptedString(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('ordine', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    op.create_table('slack_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=64), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['slack_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slack_actions')
    op.drop_table('slack_connections')
    # ### end Alembic commands ###
