"""add sort_order to menu

Revision ID: c03a84207c0b
Revises: e67c40f7981f
Create Date: 2026-02-08 18:07:33.143782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c03a84207c0b'
down_revision = 'e67c40f7981f'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('sort_order', sa.Integer(), nullable=False, server_default=sa.text("0"))
        )

    # opzionale: rimuovi il default dopo aver popolato i record esistenti
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.alter_column('sort_order', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.drop_column('sort_order')

    # ### end Alembic commands ###
