"""aggiunto campo evaded_at in SlackOrder

Revision ID: c73df253eba3
Revises: 9630fe507b6e
Create Date: 2026-02-03 17:29:20.649388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c73df253eba3'
down_revision = '9630fe507b6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slack_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evaded_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_slack_orders_evaded_at'), ['evaded_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slack_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slack_orders_evaded_at'))
        batch_op.drop_column('evaded_at')

    # ### end Alembic commands ###
