"""creazione tabella ponte assegni pagamenti

Revision ID: c8e67ef733e9
Revises: 891aae56a338
Create Date: 2026-02-24 19:56:34.299994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8e67ef733e9'
down_revision = '891aae56a338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_sale_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.Integer(), nullable=False),
    sa.Column('check_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['check_id'], ['cash_checks.id'], name=op.f('fk_cash_sale_checks_check_id_cash_checks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sale_id'], ['cash_sales.id'], name=op.f('fk_cash_sale_checks_sale_id_cash_sales'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_sale_checks')),
    sa.UniqueConstraint('sale_id', 'check_id', name='uq_sale_check')
    )
    with op.batch_alter_table('cash_sale_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_sale_checks_check_id'), ['check_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_sale_checks_sale_id'), ['sale_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_sale_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_sale_checks_sale_id'))
        batch_op.drop_index(batch_op.f('ix_cash_sale_checks_check_id'))

    op.drop_table('cash_sale_checks')
    # ### end Alembic commands ###
