"""add slack_events

Revision ID: ce6ada82fd57
Revises: bd1592341e29
Create Date: 2026-01-15 17:26:59.453959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce6ada82fd57'
down_revision = 'bd1592341e29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('trigger_type', sa.String(length=64), nullable=False),
    sa.Column('event_ts', sa.String(length=32), nullable=True),
    sa.Column('dedup_key', sa.String(length=128), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['slack_connections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slack_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slack_events_dedup_key'), ['dedup_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_slack_events_event_ts'), ['event_ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_slack_events_trigger_type'), ['trigger_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slack_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slack_events_trigger_type'))
        batch_op.drop_index(batch_op.f('ix_slack_events_event_ts'))
        batch_op.drop_index(batch_op.f('ix_slack_events_dedup_key'))

    op.drop_table('slack_events')
    # ### end Alembic commands ###
