"""Creazione tabella versioning Inventario

Revision ID: cf135a242fde
Revises: 38cd6a24c476
Create Date: 2025-08-21 17:44:39.397940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf135a242fde'
down_revision = '38cd6a24c476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventario_righe_versioni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('riga_id', sa.Integer(), nullable=True),
    sa.Column('utente_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('quantita_inserita', sa.Integer(), nullable=False),
    sa.Column('num_pedane', sa.Integer(), nullable=True),
    sa.Column('num_cartoni', sa.Integer(), nullable=True),
    sa.Column('num_pezzi_sciolti', sa.Integer(), nullable=True),
    sa.Column('ppc', sa.Integer(), nullable=True),
    sa.Column('cpp', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['riga_id'], ['inventario_righe.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utente_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventario_righe_versioni')
    # ### end Alembic commands ###
