"""modifica import conflict resolutions per hash+dato

Revision ID: cfcb3aa5ffc0
Revises: 9126721c8b3c
Create Date: 2026-01-09 07:29:16.720545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cfcb3aa5ffc0'
down_revision = '9126721c8b3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_conflict_resolutions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('db_value', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('csv_value', sa.Text(), nullable=True))
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('entity_key',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.drop_constraint('uq_icr_signature', type_='unique')
        batch_op.drop_index('ix_icr_lookup')
        batch_op.create_index('ix_icr_lookup', ['type', 'entity_key', 'field', 'mode', 'db_value_hash', 'csv_value_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_conflict_resolutions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_conflict_resolutions_csv_value_hash'), ['csv_value_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_conflict_resolutions_db_value_hash'), ['db_value_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_conflict_resolutions_entity_key'), ['entity_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_conflict_resolutions_field'), ['field'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_conflict_resolutions_type'), ['type'], unique=False)
        batch_op.drop_column('meta')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_conflict_resolutions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_import_conflict_resolutions_type'))
        batch_op.drop_index(batch_op.f('ix_import_conflict_resolutions_field'))
        batch_op.drop_index(batch_op.f('ix_import_conflict_resolutions_entity_key'))
        batch_op.drop_index(batch_op.f('ix_import_conflict_resolutions_db_value_hash'))
        batch_op.drop_index(batch_op.f('ix_import_conflict_resolutions_csv_value_hash'))
        batch_op.drop_index(batch_op.f('ix_import_conflict_resolutions_created_at'))
        batch_op.drop_index('ix_icr_lookup')
        batch_op.create_index('ix_icr_lookup', ['type', 'entity_key', 'field'], unique=False)
        batch_op.create_unique_constraint('uq_icr_signature', ['type', 'entity_key', 'field', 'db_value_hash', 'csv_value_hash'])
        batch_op.alter_column('entity_key',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('csv_value')
        batch_op.drop_column('db_value')

    # ### end Alembic commands ###
