"""Aggiunta colonna role_id a User

Revision ID: da49c0561c58
Revises: 21a4ca5e3d5d
Create Date: 2024-12-22 22:30:38.323212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da49c0561c58'
down_revision = '21a4ca5e3d5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])

        # Inserisci un ruolo predefinito nella tabella roles
    op.execute('INSERT INTO roles (id, name) VALUES (1, \'Cliente\')')

    # Imposta un valore predefinito per i record esistenti
    op.execute('UPDATE "user" SET role_id = 1')

    # Rendi la colonna NOT NULL
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role_id', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('role_id')

    op.drop_table('roles')
    # ### end Alembic commands ###
