"""aggiunta cashbank in incassi e spese

Revision ID: db627141d5e7
Revises: 8713517447a1
Create Date: 2026-03-12 14:35:30.367987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db627141d5e7'
down_revision = '8713517447a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_expense_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_cash_expense_payments_bank_id_cash_banks'), 'cash_banks', ['bank_id'], ['id'])

    with op.batch_alter_table('cash_sale_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_cash_sale_payments_bank_id_cash_banks'), 'cash_banks', ['bank_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_sale_payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cash_sale_payments_bank_id_cash_banks'), type_='foreignkey')
        batch_op.drop_column('bank_id')

    with op.batch_alter_table('cash_expense_payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cash_expense_payments_bank_id_cash_banks'), type_='foreignkey')
        batch_op.drop_column('bank_id')

    # ### end Alembic commands ###
