"""aggiunta campi export_inventario e fix_movements su tabella inventari

Revision ID: de6201d2a2a8
Revises: 0b0dc8fe99e4
Create Date: 2025-09-23 22:19:06.073492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de6201d2a2a8'
down_revision = '0b0dc8fe99e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventari', schema=None) as batch_op:
        batch_op.alter_column('export_inventario',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('fix_movements',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventari', schema=None) as batch_op:
        batch_op.alter_column('fix_movements',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('export_inventario',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
