"""aggiuntacampo bank_id in tabella CashDeposit

Revision ID: e350bce69087
Revises: bc89b1fd3896
Create Date: 2026-03-26 07:06:45.325753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e350bce69087'
down_revision = 'bc89b1fd3896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_deposits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cash_deposits_bank_id'), ['bank_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_cash_deposits_bank_id_cash_banks'), 'cash_banks', ['bank_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_deposits', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cash_deposits_bank_id_cash_banks'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_cash_deposits_bank_id'))
        batch_op.drop_column('bank_id')

    # ### end Alembic commands ###
