"""Aggiunta campi tabella articoli

Revision ID: e5f6bc284981
Revises: 2ae3c3f4bf02
Create Date: 2025-04-02 11:06:41.191439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f6bc284981'
down_revision = '2ae3c3f4bf02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articoli', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pezzi_per_collo', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('colli_per_pedana', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articoli', schema=None) as batch_op:
        batch_op.drop_column('colli_per_pedana')
        batch_op.drop_column('pezzi_per_collo')

    # ### end Alembic commands ###
