"""cash customers anagrafica + aliases

Revision ID: e69414835af3
Revises: 7ee042625cc9
Create Date: 2026-03-03 10:23:30.265228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e69414835af3'
down_revision = '7ee042625cc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_customer_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('alias_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['cash_customers.id'], name=op.f('fk_cash_customer_aliases_customer_id_cash_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_customer_aliases')),
    sa.UniqueConstraint('customer_id', 'alias', name='uq_cash_customer_alias_customer_alias')
    )
    with op.batch_alter_table('cash_customer_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_customer_aliases_alias'), ['alias'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_customer_aliases_customer_id'), ['customer_id'], unique=False)

    with op.batch_alter_table('cash_customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ragione_sociale', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('partita_iva', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('codice_cliente', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('display_name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_constraint('uq_cash_customers_display_name', type_='unique')
        batch_op.create_index(batch_op.f('ix_cash_customers_codice_cliente'), ['codice_cliente'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_customers_display_name'), ['display_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_customers_partita_iva'), ['partita_iva'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_customers_ragione_sociale'), ['ragione_sociale'], unique=False)
        batch_op.drop_column('is_active')
        batch_op.drop_column('notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_cash_customers_ragione_sociale'))
        batch_op.drop_index(batch_op.f('ix_cash_customers_partita_iva'))
        batch_op.drop_index(batch_op.f('ix_cash_customers_display_name'))
        batch_op.drop_index(batch_op.f('ix_cash_customers_codice_cliente'))
        batch_op.create_unique_constraint('uq_cash_customers_display_name', ['display_name'])
        batch_op.alter_column('display_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('codice_cliente')
        batch_op.drop_column('partita_iva')
        batch_op.drop_column('ragione_sociale')

    with op.batch_alter_table('cash_customer_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_customer_aliases_customer_id'))
        batch_op.drop_index(batch_op.f('ix_cash_customer_aliases_alias'))

    op.drop_table('cash_customer_aliases')
    # ### end Alembic commands ###
