"""aggiunta tabella assegni

Revision ID: ec627f9faa19
Revises: 149261200f9b
Create Date: 2026-02-21 07:10:24.831533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec627f9faa19'
down_revision = '149261200f9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_number', sa.String(length=64), nullable=False),
    sa.Column('abi', sa.String(length=5), nullable=True),
    sa.Column('cab', sa.String(length=5), nullable=True),
    sa.Column('bank_name', sa.String(length=120), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['cash_customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_name', 'check_number', name='uq_check_bank_number')
    )
    with op.batch_alter_table('cash_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_checks_abi'), ['abi'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_checks_cab'), ['cab'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_checks_check_number'), ['check_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_checks_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_checks_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pos_device_circuits', schema=None) as batch_op:
        batch_op.drop_constraint('uq_pos_device_circuit', type_='unique')

    with op.batch_alter_table('cash_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_checks_status'))
        batch_op.drop_index(batch_op.f('ix_cash_checks_customer_id'))
        batch_op.drop_index(batch_op.f('ix_cash_checks_check_number'))
        batch_op.drop_index(batch_op.f('ix_cash_checks_cab'))
        batch_op.drop_index(batch_op.f('ix_cash_checks_abi'))

    op.drop_table('cash_checks')
    # ### end Alembic commands ###
