"""aggiunta colonna con icon in PosCircuit

Revision ID: ed6f0371664f
Revises: c8e67ef733e9
Create Date: 2026-02-25 17:25:15.670920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed6f0371664f'
down_revision = 'c8e67ef733e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pos_circuits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pos_circuits', schema=None) as batch_op:
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
