"""Aggiunta campo schema_json alla tabella trello_connections

Revision ID: f94496b971b6
Revises: 6233822b2b83
Create Date: 2025-05-14 07:31:26.078086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f94496b971b6'
down_revision = '6233822b2b83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trello_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schema_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trello_connections', schema=None) as batch_op:
        batch_op.drop_column('schema_json')

    # ### end Alembic commands ###
