"""Aggiunta campo ordine alla tabella trello_actions

Revision ID: ff1ef31e84a8
Revises: ae3da00ba8aa
Create Date: 2025-06-06 15:04:58.382202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff1ef31e84a8'
down_revision = 'ae3da00ba8aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trello_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ordine', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trello_connections', schema=None) as batch_op:
        batch_op.drop_column('ordine')

    # ### end Alembic commands ###
