name: Deploy to Production

on:
  workflow_dispatch: # Permette l'esecuzione manuale del workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug SSH key
        run: ssh -T ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} -p ${{ secrets.SERVER_PORT }}
    
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # Sostituisci con la tua versione di Python

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Deploy to server
        uses: shimataro/ssh-key-action@v2
        with:
        key: ${{ secrets.SERVER_KEY }}
        known_hosts: 'just-a-placeholder-so-known_hosts-is-not-empty'
        script: |
          cd /home/tecno/ld-flask-app-working # Percorso della tua app sul server
          git pull origin main # Aggiorna il codice dal branch main
          source venv/bin/activate # Attiva l'ambiente virtuale
          pip install -r requirements.txt # Aggiorna le dipendenze
          sudo systemctl restart ld-flask-app
